print('Digite 3 números')
n1 = float(input('Número 1:'))
n2 = float(input('Número 2:'))
n3 = float(input('Número 3:'))
print('O número maior é: {}'.format(max(n1, n2, n3)))
print('O menor número é: {}'.format(min(n1, n2, n3)))
